from django.urls import path

from . import views

app_name = 'projects'

urlpatterns = [
    path('projects/new/', views.ProjectCreateView.as_view(), name='create'),
    path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='detail'),
    path(
        'projects/<int:pk>/actions/',
        views.ProjectActionCenterView.as_view(),
        name='action_center',
    ),
    path(
        'projects/<int:pk>/edit/',
        views.ProjectUpdateView.as_view(),
        name='edit',
    ),
    path(
        'projects/<int:pk>/people/',
        views.ProjectPeopleView.as_view(),
        name='people',
    ),
    path(
        'projects/<int:pk>/messages/',
        views.ProjectMessageListView.as_view(),
        name='message_list',
    ),
    path(
        'projects/<int:pk>/messages/new/',
        views.ProjectMessageCreateView.as_view(),
        name='message_create',
    ),
    path(
        'projects/<int:pk>/messages/<int:thread_pk>/',
        views.ProjectMessageThreadView.as_view(),
        name='message_thread',
    ),
    path(
        'projects/<int:pk>/messages/<int:thread_pk>/<str:action>/',
        views.ProjectMessageStatusView.as_view(),
        name='message_status',
    ),
    path(
        'projects/<int:pk>/documents/',
        views.ProjectDocumentListView.as_view(),
        name='document_list',
    ),
    path(
        'projects/<int:pk>/documents/new/',
        views.ProjectDocumentCreateView.as_view(),
        name='document_create',
    ),
    path(
        'projects/<int:pk>/documents/<int:document_pk>/',
        views.ProjectDocumentDetailView.as_view(),
        name='document_detail',
    ),
    path(
        'projects/<int:pk>/documents/<int:document_pk>/versions/new/',
        views.ProjectDocumentVersionCreateView.as_view(),
        name='document_version_create',
    ),
    path(
        'projects/<int:pk>/documents/<int:document_pk>/versions/<int:version_pk>/download/',
        views.ProjectDocumentDownloadView.as_view(),
        name='document_download',
    ),
    path(
        'projects/<int:pk>/documents/<int:document_pk>/decision/',
        views.ProjectDocumentDecisionView.as_view(),
        name='document_decision',
    ),
    path(
        'projects/<int:pk>/change-orders/',
        views.ChangeOrderListView.as_view(),
        name='change_order_list',
    ),
    path(
        'projects/<int:pk>/change-orders/new/',
        views.ChangeOrderCreateView.as_view(),
        name='change_order_create',
    ),
    path(
        'projects/<int:pk>/change-orders/<int:change_order_pk>/',
        views.ChangeOrderDetailView.as_view(),
        name='change_order_detail',
    ),
    path(
        'projects/<int:pk>/change-orders/<int:change_order_pk>/edit/',
        views.ChangeOrderUpdateView.as_view(),
        name='change_order_edit',
    ),
    path(
        'projects/<int:pk>/change-orders/<int:change_order_pk>/submit/',
        views.ChangeOrderSubmitView.as_view(),
        name='change_order_submit',
    ),
    path(
        'projects/<int:pk>/change-orders/<int:change_order_pk>/decision/',
        views.ChangeOrderDecisionView.as_view(),
        name='change_order_decision',
    ),
    path(
        'projects/<int:pk>/change-orders/<int:change_order_pk>/void/',
        views.ChangeOrderVoidView.as_view(),
        name='change_order_void',
    ),
    path(
        'projects/<int:pk>/selections/',
        views.FinishSelectionListView.as_view(),
        name='selection_list',
    ),
    path(
        'projects/<int:pk>/selections/new/',
        views.FinishSelectionCreateView.as_view(),
        name='selection_create',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/',
        views.FinishSelectionDetailView.as_view(),
        name='selection_detail',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/edit/',
        views.FinishSelectionUpdateView.as_view(),
        name='selection_edit',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/options/new/',
        views.SelectionOptionCreateView.as_view(),
        name='selection_option_create',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/options/<int:option_pk>/edit/',
        views.SelectionOptionUpdateView.as_view(),
        name='selection_option_edit',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/options/<int:option_pk>/delete/',
        views.SelectionOptionDeleteView.as_view(),
        name='selection_option_delete',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/publish/',
        views.FinishSelectionPublishView.as_view(),
        name='selection_publish',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/choose/',
        views.FinishSelectionChooseView.as_view(),
        name='selection_choose',
    ),
    path(
        'projects/<int:pk>/selections/<int:selection_pk>/void/',
        views.FinishSelectionVoidView.as_view(),
        name='selection_void',
    ),
    path(
        'projects/<int:pk>/schedule/',
        views.ProjectScheduleView.as_view(),
        name='schedule',
    ),
    path(
        'projects/<int:pk>/schedule/new/',
        views.ScheduleMilestoneCreateView.as_view(),
        name='schedule_milestone_create',
    ),
    path(
        'projects/<int:pk>/schedule/<int:milestone_pk>/edit/',
        views.ScheduleMilestoneUpdateView.as_view(),
        name='schedule_milestone_edit',
    ),
    path(
        'projects/<int:pk>/invite-client/',
        views.ClientInviteView.as_view(),
        name='invite_client',
    ),
    path(
        'projects/<int:pk>/invitations/<int:invitation_pk>/resend/',
        views.ProjectInvitationResendView.as_view(),
        name='resend_client_invitation',
    ),
    path(
        'projects/<int:pk>/invitations/<int:invitation_pk>/revoke/',
        views.ProjectInvitationRevokeView.as_view(),
        name='revoke_client_invitation',
    ),
    path(
        'projects/<int:pk>/members/<int:membership_pk>/<str:action>/',
        views.ProjectMemberAccessView.as_view(),
        name='project_member_access',
    ),
    path(
        'invitations/<uuid:token>/',
        views.InvitationAcceptView.as_view(),
        name='accept_invitation',
    ),
    path('companies/', views.CompanyListView.as_view(), name='company_list'),
    path(
        'companies/<slug:slug>/team/',
        views.CompanyTeamView.as_view(),
        name='company_team',
    ),
    path(
        'companies/<slug:slug>/team/invite/',
        views.TeamInviteView.as_view(),
        name='invite_team_member',
    ),
    path(
        'companies/<slug:slug>/team/invitations/<int:invitation_pk>/resend/',
        views.TeamInvitationResendView.as_view(),
        name='resend_team_invitation',
    ),
    path(
        'companies/<slug:slug>/team/invitations/<int:invitation_pk>/revoke/',
        views.TeamInvitationRevokeView.as_view(),
        name='revoke_team_invitation',
    ),
    path(
        'companies/<slug:slug>/team/members/<int:membership_pk>/update/',
        views.TeamMembershipUpdateView.as_view(),
        name='update_team_membership',
    ),
    path(
        'team-invitations/<uuid:token>/',
        views.TeamInvitationAcceptView.as_view(),
        name='accept_team_invitation',
    ),
]
