# Generated by Django 6.0.3 on 2026-08-01 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0016_alter_activityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('voided', 'Voided')], default='draft', max_length=20)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='projects.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='projects.project')),
                ('source_change_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='projects.changeorder')),
                ('source_selection', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='projects.finishselection')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-number', '-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('material', 'Material'), ('labor', 'Labor'), ('subcontractor', 'Subcontractor'), ('commission', 'Commission/markup'), ('tax', 'Tax'), ('allowance', 'Allowance'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='billing.invoice')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('organization', 'number'), name='billing_unique_invoice_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal_amount__gte', 0)), name='billing_invoice_subtotal_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_amount__gte', 0)), name='billing_invoice_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='billing_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gte', 0), ('amount_paid__lte', models.F('total_amount'))), name='billing_invoice_paid_within_total'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('source_change_order__isnull', False), ('source_selection__isnull', False), _negated=True), name='billing_invoice_one_source_type'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='billing_invoice_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='billing_invoice_line_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issue_date__isnull', True), ('issued_at__isnull', True), ('issued_by__isnull', True), ('number__isnull', True), ('status', 'draft')), models.Q(('issue_date__isnull', False), ('issued_at__isnull', False), ('issued_by__isnull', False), ('number__isnull', False), ('status__in', ('issued', 'partially_paid', 'paid', 'voided'))), _connector='OR'), name='billing_invoice_issue_fields_match_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'voided'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(models.Q(('status', 'voided'), _negated=True), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='billing_invoice_void_fields_match_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('amount_paid', 0), ('status__in', ('draft', 'issued', 'voided'))), models.Q(('status', 'partially_paid'), ('amount_paid__gt', 0), ('amount_paid__lt', models.F('total_amount'))), models.Q(('amount_paid', models.F('total_amount')), ('status', 'paid')), _connector='OR'), name='billing_invoice_payment_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'draft'), ('total_amount__gt', 0), _connector='OR'), name='billing_issued_invoice_total_positive'),
        ),
    ]
