# Generated by Django 6.0.3 on 2026-08-03 12:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoicelineitem_cost_code_payment'),
        ('projects', '0021_estimate_subtotal_total_estimate_tax_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Tax percentage, e.g. 7.250 for 7.25%. Tax is computed automatically from this rate.', max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='billing_invoice_tax_rate_within_range'),
        ),
    ]
