# Generated by Django 6.0.3 on 2026-08-05 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_tax_rate_and_more'),
        ('projects', '0025_changeorder_source_selection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('check', 'Check'), ('ach', 'ACH/bank transfer'), ('card', 'Card'), ('cash', 'Cash'), ('credit_memo', 'Credit memo'), ('other', 'Other')], default='other', max_length=12),
        ),
        migrations.CreateModel(
            name='CreditMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('voided', 'Voided')], default='draft', max_length=10)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos_created', to=settings.AUTH_USER_MODEL)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos_issued', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos', to='projects.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos', to='projects.project')),
                ('source_change_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memo', to='projects.changeorder')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_memos_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-number', '-created_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_memo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='billing.creditmemo'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_memo__isnull', False), ('method', 'credit_memo')), models.Q(models.Q(('method', 'credit_memo'), _negated=True), ('credit_memo__isnull', True)), _connector='OR'), name='billing_payment_credit_memo_matches_method'),
        ),
        migrations.AddConstraint(
            model_name='creditmemo',
            constraint=models.UniqueConstraint(condition=models.Q(('number__isnull', False)), fields=('organization', 'number'), name='billing_unique_credit_memo_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='creditmemo',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='billing_credit_memo_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='creditmemo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('issued_at__isnull', True), ('issued_by__isnull', True), ('number__isnull', True), ('status', 'draft')), models.Q(('issued_at__isnull', False), ('issued_by__isnull', False), ('number__isnull', False), ('status__in', ('issued', 'voided'))), _connector='OR'), name='billing_credit_memo_issue_fields_match_status'),
        ),
        migrations.AddConstraint(
            model_name='creditmemo',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'voided'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(models.Q(('status', 'voided'), _negated=True), ('void_reason', ''), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='billing_credit_memo_void_fields_match_status'),
        ),
    ]
