# Generated by Django 6.0.3 on 2026-08-05 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_payment_method_creditmemo_payment_credit_memo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='payment',
            name='billing_payment_credit_memo_matches_method',
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('credit_memo__isnull', True), ('method', 'credit_memo'), _connector='OR'), name='billing_payment_credit_memo_matches_method'),
        ),
    ]
