# Generated by Django 6.0.3 on 2026-07-23 21:39

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.organization'),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_invitations_accepted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectinvitation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_memberships_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='organizationmembership',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='projects_unique_organization_user'),
        ),
        migrations.AddConstraint(
            model_name='projectinvitation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('project'), condition=models.Q(('accepted_at__isnull', True), ('revoked_at__isnull', True)), name='projects_unique_pending_invite_email'),
        ),
        migrations.AddConstraint(
            model_name='projectmembership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='projects_unique_project_user'),
        ),
    ]
