# Generated by Django 6.0.3 on 2026-07-24 00:59

import django.db.models.deletion
import projects.models
import projects.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_activityevent_event_type_conversationthread_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('document_decision_recorded', 'Document decision recorded')], max_length=40),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('plan', 'Plan or drawing'), ('contract', 'Contract'), ('selection', 'Selection'), ('change_order', 'Change order'), ('other', 'Other')], default='general', max_length=20)),
                ('client_visible', models.BooleanField(default=True)),
                ('requires_client_approval', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_documents_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
            options={
                'ordering': ('title', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ProjectDocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(storage=projects.storage.PrivateDocumentStorage(), upload_to=projects.models.project_document_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.projectdocument')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_document_versions_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-version_number', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='DocumentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_decisions', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.projectdocumentversion')),
            ],
            options={
                'ordering': ('decided_at', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='projectdocumentversion',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='projects_unique_document_version_number'),
        ),
        migrations.AddConstraint(
            model_name='documentdecision',
            constraint=models.UniqueConstraint(fields=('version', 'decided_by'), name='projects_unique_document_decision_per_user_version'),
        ),
    ]
