# Generated by Django 6.0.3 on 2026-07-24 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_activityevent_event_type_projectdocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided')], max_length=40),
        ),
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('schedule_delta_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting client'), ('approved', 'Approved'), ('declined', 'Declined'), ('voided', 'Voided')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('client_comment', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_orders_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orders_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_orders', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orders_submitted', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_orders_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-number', '-pk'),
                'constraints': [models.UniqueConstraint(fields=('project', 'number'), name='projects_unique_change_order_number_per_project'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('status__in', ('pending', 'approved', 'declined', 'voided')), ('submitted_at__isnull', False), ('submitted_by__isnull', False)), _connector='OR'), name='projects_change_order_submission_matches_status'), models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ('approved', 'declined'))), models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status__in', ('draft', 'pending', 'voided'))), _connector='OR'), name='projects_change_order_decision_matches_status'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'voided'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(('status__in', ('draft', 'pending', 'approved', 'declined')), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='projects_change_order_void_matches_status')],
            },
        ),
    ]
