# Generated by Django 6.0.3 on 2026-07-24 11:17

import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_activityevent_event_type_changeorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_voided', 'Selection voided')], max_length=40),
        ),
        migrations.CreateModel(
            name='FinishSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('allowance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Awaiting client'), ('selected', 'Selected'), ('voided', 'Voided')], default='draft', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('selected_at', models.DateTimeField(blank=True, null=True)),
                ('client_comment', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finish_selections_created', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finish_selections_opened', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finish_selections', to='projects.project')),
                ('selected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finish_selections_made', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finish_selections_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-number', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SelectionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='projects.finishselection')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='finishselection',
            name='chosen_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chosen_for_selections', to='projects.selectionoption'),
        ),
        migrations.AddConstraint(
            model_name='selectionoption',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('selection'), name='projects_unique_selection_option_name'),
        ),
        migrations.AddConstraint(
            model_name='finishselection',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='projects_unique_selection_number_per_project'),
        ),
        migrations.AddConstraint(
            model_name='finishselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('opened_at__isnull', True), ('opened_by__isnull', True), ('status', 'draft')), models.Q(('opened_at__isnull', False), ('opened_by__isnull', False), ('status__in', ('open', 'selected', 'voided'))), _connector='OR'), name='projects_selection_open_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='finishselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('chosen_option__isnull', False), ('selected_at__isnull', False), ('selected_by__isnull', False), ('status', 'selected')), models.Q(('chosen_option__isnull', True), ('selected_at__isnull', True), ('selected_by__isnull', True), ('status__in', ('draft', 'open', 'voided'))), _connector='OR'), name='projects_selection_choice_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='finishselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'voided'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(('status__in', ('draft', 'open', 'selected')), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='projects_selection_void_matches_status'),
        ),
    ]
