# Generated by Django 6.0.3 on 2026-07-24 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_activityevent_event_type_finishselection_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_voided', 'Selection voided'), ('schedule_milestone_created', 'Schedule milestone created'), ('schedule_milestone_updated', 'Schedule milestone updated')], max_length=40),
        ),
        migrations.CreateModel(
            name='ScheduleMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=15)),
                ('client_visible', models.BooleanField(default=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_milestones_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_milestones', to='projects.project')),
            ],
            options={
                'ordering': ('start_date', 'sort_order', 'pk'),
            },
        ),
    ]
