# Generated by Django 6.0.3 on 2026-07-31 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_internal_users(apps, schema_editor):
    organization_membership = apps.get_model('projects', 'OrganizationMembership')
    project = apps.get_model('projects', 'Project')
    project_internal_access = apps.get_model('projects', 'ProjectInternalAccess')
    schedule_milestone = apps.get_model('projects', 'ScheduleMilestone')

    for membership in organization_membership.objects.filter(
        is_active=True,
        role__in=('staff', 'accountant'),
    ).iterator():
        can_manage = membership.role == 'staff'
        project_internal_access.objects.bulk_create(
            [
                project_internal_access(
                    project_id=project_id,
                    membership_id=membership.pk,
                    can_manage=can_manage,
                    can_invite_clients=can_manage,
                    receives_notifications=True,
                    is_active=True,
                )
                for project_id in project.objects.filter(
                    organization_id=membership.organization_id
                ).values_list('pk', flat=True)
            ],
            ignore_conflicts=True,
        )

    schedule_milestone.objects.update(client_visible=False)


def remove_existing_internal_assignments(apps, schema_editor):
    apps.get_model('projects', 'ProjectInternalAccess').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_activityevent_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('internal_access_assigned', 'Internal project access assigned'), ('internal_access_updated', 'Internal project access updated'), ('internal_access_revoked', 'Internal project access revoked'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('client_upload_created', 'Client upload created'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_reopened', 'Selection reopened'), ('selection_voided', 'Selection voided'), ('schedule_milestone_created', 'Schedule milestone created'), ('schedule_milestone_updated', 'Schedule milestone updated')], max_length=40),
        ),
        migrations.AlterField(
            model_name='organizationinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('project_manager', 'Project manager'), ('staff', 'Staff'), ('office_manager', 'Office manager'), ('real_estate_agent', 'Real estate agent'), ('accountant', 'Accountant')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('project_manager', 'Project manager'), ('staff', 'Staff'), ('office_manager', 'Office manager'), ('real_estate_agent', 'Real estate agent'), ('accountant', 'Accountant'), ('client', 'Client'), ('subcontractor', 'Subcontractor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('plan', 'Plan or drawing'), ('contract', 'Contract'), ('selection', 'Selection'), ('change_order', 'Change order'), ('client_upload', 'Client upload'), ('other', 'Other')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='schedulemilestone',
            name='client_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProjectInternalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_manage', models.BooleanField(default=False)),
                ('can_invite_clients', models.BooleanField(default=False)),
                ('receives_notifications', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_internal_access_assignments', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_access', to='projects.organizationmembership')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_access', to='projects.project')),
            ],
            options={
                'ordering': ('membership__user__email',),
                'constraints': [models.UniqueConstraint(fields=('project', 'membership'), name='projects_unique_internal_access')],
            },
        ),
        migrations.RunPython(
            assign_existing_internal_users,
            remove_existing_internal_assignments,
        ),
    ]
