# Generated by Django 6.0.3 on 2026-07-31 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_activityevent_event_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrderDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('decided_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='ChangeOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('material', 'Material'), ('labor', 'Labor'), ('subcontractor', 'Subcontractor'), ('commission', 'Commission/markup'), ('tax', 'Tax'), ('allowance', 'Allowance'), ('other', 'Other')], default='other', max_length=20)),
                ('cost_code', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='changeorder',
            name='replaces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='projects.changeorder'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='requires_financial_reversal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='required_approvals',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('internal_access_assigned', 'Internal project access assigned'), ('internal_access_updated', 'Internal project access updated'), ('internal_access_revoked', 'Internal project access revoked'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('client_upload_created', 'Client upload created'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('change_order_revised', 'Change order revised'), ('change_order_replacement_created', 'Change order replacement created'), ('change_order_line_item_added', 'Change order line item added'), ('change_order_line_item_updated', 'Change order line item updated'), ('change_order_line_item_removed', 'Change order line item removed'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_reopened', 'Selection reopened'), ('selection_voided', 'Selection voided'), ('schedule_milestone_created', 'Schedule milestone created'), ('schedule_milestone_updated', 'Schedule milestone updated')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='changeorder',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'voided'), ('requires_financial_reversal', False), _connector='OR'), name='projects_change_order_reversal_requires_voided'),
        ),
        migrations.AddField(
            model_name='changeorderdecision',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.changeorder'),
        ),
        migrations.AddField(
            model_name='changeorderdecision',
            name='decided_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_order_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='change_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.changeorder'),
        ),
        migrations.AddConstraint(
            model_name='changeorderdecision',
            constraint=models.UniqueConstraint(fields=('change_order', 'decided_by'), name='projects_unique_change_order_decision_per_user'),
        ),
    ]
