# Generated by Django 6.0.3 on 2026-07-31 22:39

import django.db.models.deletion
import django.db.models.functions.text
import projects.models
import projects.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_changeorderdecision_changeorderlineitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='finishselection',
            name='credit_disposition',
            field=models.CharField(choices=[('undetermined', 'Undetermined'), ('apply_elsewhere', 'Apply to another selection'), ('return_at_closing', 'Return at closing'), ('retain_as_margin', 'Retain as project margin')], default='undetermined', max_length=20),
        ),
        migrations.AddField(
            model_name='finishselection',
            name='credit_disposition_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finishselection',
            name='credit_disposition_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finish_selection_credit_dispositions_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='selectionoption',
            name='attachment',
            field=models.FileField(blank=True, null=True, storage=projects.storage.PrivateDocumentStorage(), upload_to=projects.models.selection_option_upload_path),
        ),
        migrations.AddField(
            model_name='selectionoption',
            name='image',
            field=models.FileField(blank=True, null=True, storage=projects.storage.PrivateDocumentStorage(), upload_to=projects.models.selection_option_upload_path),
        ),
        migrations.AddField(
            model_name='selectionoption',
            name='lead_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='selectionoption',
            name='product_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='selectionoption',
            name='specification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='selectionoption',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('internal_access_assigned', 'Internal project access assigned'), ('internal_access_updated', 'Internal project access updated'), ('internal_access_revoked', 'Internal project access revoked'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('client_upload_created', 'Client upload created'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('change_order_revised', 'Change order revised'), ('change_order_replacement_created', 'Change order replacement created'), ('change_order_line_item_added', 'Change order line item added'), ('change_order_line_item_updated', 'Change order line item updated'), ('change_order_line_item_removed', 'Change order line item removed'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_reopened', 'Selection reopened'), ('selection_voided', 'Selection voided'), ('selection_package_created', 'Selection package created'), ('selection_custom_request_submitted', 'Selection custom request submitted'), ('selection_custom_request_reviewed', 'Selection custom request reviewed'), ('selection_credit_disposition_set', 'Selection credit disposition set'), ('selection_reminder_sent', 'Selection reminder sent'), ('schedule_milestone_created', 'Schedule milestone created'), ('schedule_milestone_updated', 'Schedule milestone updated')], max_length=40),
        ),
        migrations.CreateModel(
            name='SelectionCustomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('reviewed', 'Reviewed')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_custom_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selection_custom_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_requests', to='projects.finishselection')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='SelectionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selection_packages_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selection_packages', to='projects.project')),
            ],
            options={
                'ordering': ('title', 'pk'),
            },
        ),
        migrations.AddField(
            model_name='finishselection',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choices', to='projects.selectionpackage'),
        ),
        migrations.AddConstraint(
            model_name='finishselection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_disposition', 'undetermined'), ('credit_disposition_set_at__isnull', True), ('credit_disposition_set_by__isnull', True)), models.Q(('credit_disposition__in', ('apply_elsewhere', 'return_at_closing', 'retain_as_margin')), ('credit_disposition_set_at__isnull', False), ('credit_disposition_set_by__isnull', False)), _connector='OR'), name='projects_selection_credit_disposition_matches_actor'),
        ),
        migrations.AddConstraint(
            model_name='selectioncustomrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reviewed_at__isnull', True), ('reviewed_by__isnull', True), ('status', 'pending')), models.Q(('reviewed_at__isnull', False), ('reviewed_by__isnull', False), ('status', 'reviewed')), _connector='OR'), name='projects_selection_custom_request_review_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='selectionpackage',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('project'), name='projects_unique_selection_package_title'),
        ),
    ]
