# Generated by Django 6.0.3 on 2026-08-02 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_activityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('internal_access_assigned', 'Internal project access assigned'), ('internal_access_updated', 'Internal project access updated'), ('internal_access_revoked', 'Internal project access revoked'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('client_upload_created', 'Client upload created'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('change_order_revised', 'Change order revised'), ('change_order_replacement_created', 'Change order replacement created'), ('change_order_line_item_added', 'Change order line item added'), ('change_order_line_item_updated', 'Change order line item updated'), ('change_order_line_item_removed', 'Change order line item removed'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_reopened', 'Selection reopened'), ('selection_voided', 'Selection voided'), ('selection_package_created', 'Selection package created'), ('selection_custom_request_submitted', 'Selection custom request submitted'), ('selection_custom_request_reviewed', 'Selection custom request reviewed'), ('selection_credit_disposition_set', 'Selection credit disposition set'), ('selection_reminder_sent', 'Selection reminder sent'), ('schedule_milestone_created', 'Schedule milestone created'), ('schedule_milestone_updated', 'Schedule milestone updated'), ('quickbooks_connected', 'QuickBooks connected'), ('quickbooks_reconnected', 'QuickBooks reconnected'), ('quickbooks_disconnected', 'QuickBooks disconnected'), ('quickbooks_capabilities_refreshed', 'QuickBooks capabilities refreshed'), ('quickbooks_project_mapped', 'Project mapped to QuickBooks customer'), ('quickbooks_project_unlinked', 'Project unlinked from QuickBooks customer'), ('quickbooks_project_mapping_tombstoned', 'QuickBooks customer mapping tombstoned'), ('quickbooks_customer_sync_succeeded', 'QuickBooks customer sync succeeded'), ('quickbooks_customer_sync_failed', 'QuickBooks customer sync failed'), ('quickbooks_sync_resolved', 'QuickBooks sync issue resolved'), ('quickbooks_invoice_mapped', 'QuickBooks invoice mapped'), ('invoice_draft_created', 'Invoice draft created'), ('invoice_draft_discarded', 'Invoice draft discarded'), ('invoice_issued', 'Invoice issued'), ('invoice_voided', 'Invoice voided'), ('payment_recorded', 'Payment recorded'), ('payment_deleted', 'Payment deleted'), ('estimate_created', 'Estimate created'), ('estimate_updated', 'Estimate updated'), ('estimate_submitted', 'Estimate submitted'), ('estimate_decided', 'Estimate decided'), ('estimate_voided', 'Estimate voided'), ('estimate_line_item_added', 'Estimate line item added'), ('estimate_line_item_updated', 'Estimate line item updated'), ('estimate_line_item_removed', 'Estimate line item removed')], max_length=40),
        ),
        migrations.CreateModel(
            name='CostCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_codes', to='projects.organization')),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.RemoveField(
            model_name='changeorderlineitem',
            name='cost_code',
        ),
        migrations.AddField(
            model_name='changeorderlineitem',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='change_order_line_items', to='projects.costcode'),
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Awaiting client'), ('approved', 'Approved'), ('declined', 'Declined'), ('voided', 'Voided')], default='draft', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('client_comment', models.TextField(blank=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('required_approvals', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates_decided', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='projects.project')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates_submitted', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-number', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='EstimateDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('declined', 'Declined')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_decisions', to=settings.AUTH_USER_MODEL)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.estimate')),
            ],
            options={
                'ordering': ('decided_at', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EstimateLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('material', 'Material'), ('labor', 'Labor'), ('subcontractor', 'Subcontractor'), ('commission', 'Commission/markup'), ('tax', 'Tax'), ('allowance', 'Allowance'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimate_line_items', to='projects.costcode')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='projects.estimate')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='costcode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='projects_unique_cost_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.UniqueConstraint(fields=('project', 'number'), name='projects_unique_estimate_number_per_project'),
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('project',), name='projects_unique_approved_estimate_per_project'),
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'draft'), ('submitted_at__isnull', True), ('submitted_by__isnull', True)), models.Q(('status__in', ('pending', 'approved', 'declined', 'voided')), ('submitted_at__isnull', False), ('submitted_by__isnull', False)), _connector='OR'), name='projects_estimate_submission_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('decided_at__isnull', False), ('decided_by__isnull', False), ('status__in', ('approved', 'declined'))), models.Q(('decided_at__isnull', True), ('decided_by__isnull', True), ('status__in', ('draft', 'pending', 'voided'))), _connector='OR'), name='projects_estimate_decision_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'voided'), ('voided_at__isnull', False), ('voided_by__isnull', False)), models.Q(('status__in', ('draft', 'pending', 'approved', 'declined')), ('voided_at__isnull', True), ('voided_by__isnull', True)), _connector='OR'), name='projects_estimate_void_matches_status'),
        ),
        migrations.AddConstraint(
            model_name='estimatedecision',
            constraint=models.UniqueConstraint(fields=('estimate', 'decided_by'), name='projects_unique_estimate_decision_per_user'),
        ),
    ]
