# Generated by Django 6.0.3 on 2026-08-02 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_project_contract_amount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='event_type',
            field=models.CharField(choices=[('project_created', 'Project created'), ('project_updated', 'Project updated'), ('client_invited', 'Client invited'), ('client_invite_resent', 'Client invitation resent'), ('client_invite_revoked', 'Client invitation revoked'), ('client_joined', 'Client joined'), ('client_access_revoked', 'Client access revoked'), ('client_access_restored', 'Client access restored'), ('team_invited', 'Team member invited'), ('team_invite_resent', 'Team invitation resent'), ('team_invite_revoked', 'Team invitation revoked'), ('team_joined', 'Team member joined'), ('team_role_changed', 'Team role changed'), ('team_access_changed', 'Team access changed'), ('internal_access_assigned', 'Internal project access assigned'), ('internal_access_updated', 'Internal project access updated'), ('internal_access_revoked', 'Internal project access revoked'), ('message_thread_created', 'Message thread created'), ('message_sent', 'Message sent'), ('message_thread_status_changed', 'Message thread status changed'), ('document_created', 'Document created'), ('document_version_added', 'Document version added'), ('client_upload_created', 'Client upload created'), ('document_decision_recorded', 'Document decision recorded'), ('change_order_created', 'Change order created'), ('change_order_updated', 'Change order updated'), ('change_order_submitted', 'Change order submitted'), ('change_order_decided', 'Change order decided'), ('change_order_voided', 'Change order voided'), ('change_order_revised', 'Change order revised'), ('change_order_replacement_created', 'Change order replacement created'), ('change_order_line_item_added', 'Change order line item added'), ('change_order_line_item_updated', 'Change order line item updated'), ('change_order_line_item_removed', 'Change order line item removed'), ('selection_created', 'Selection created'), ('selection_updated', 'Selection updated'), ('selection_option_added', 'Selection option added'), ('selection_option_updated', 'Selection option updated'), ('selection_option_removed', 'Selection option removed'), ('selection_published', 'Selection published'), ('selection_chosen', 'Selection chosen'), ('selection_reopened', 'Selection reopened'), ('selection_voided', 'Selection voided'), ('selection_package_created', 'Selection package created'), ('selection_custom_request_submitted', 'Selection custom request submitted'), ('selection_custom_request_reviewed', 'Selection custom request reviewed'), ('selection_credit_disposition_set', 'Selection credit disposition set'), ('selection_reminder_sent', 'Selection reminder sent'), ('schedule_milestone_created', 'Schedule milestone created'), ('schedule_milestone_updated', 'Schedule milestone updated'), ('quickbooks_connected', 'QuickBooks connected'), ('quickbooks_reconnected', 'QuickBooks reconnected'), ('quickbooks_disconnected', 'QuickBooks disconnected'), ('quickbooks_capabilities_refreshed', 'QuickBooks capabilities refreshed'), ('quickbooks_project_mapped', 'Project mapped to QuickBooks customer'), ('quickbooks_project_unlinked', 'Project unlinked from QuickBooks customer'), ('quickbooks_project_mapping_tombstoned', 'QuickBooks customer mapping tombstoned'), ('quickbooks_customer_sync_succeeded', 'QuickBooks customer sync succeeded'), ('quickbooks_customer_sync_failed', 'QuickBooks customer sync failed'), ('quickbooks_sync_resolved', 'QuickBooks sync issue resolved'), ('quickbooks_invoice_mapped', 'QuickBooks invoice mapped'), ('invoice_draft_created', 'Invoice draft created'), ('invoice_draft_discarded', 'Invoice draft discarded'), ('invoice_issued', 'Invoice issued'), ('invoice_voided', 'Invoice voided'), ('payment_recorded', 'Payment recorded'), ('payment_deleted', 'Payment deleted'), ('estimate_created', 'Estimate created'), ('estimate_updated', 'Estimate updated'), ('estimate_submitted', 'Estimate submitted'), ('estimate_decided', 'Estimate decided'), ('estimate_voided', 'Estimate voided'), ('estimate_line_item_added', 'Estimate line item added'), ('estimate_line_item_updated', 'Estimate line item updated'), ('estimate_line_item_removed', 'Estimate line item removed'), ('project_cost_entry_recorded', 'Actual cost recorded'), ('project_cost_entry_deleted', 'Actual cost deleted')], max_length=40),
        ),
        migrations.CreateModel(
            name='ProjectCostEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('product', 'Product'), ('material', 'Material'), ('labor', 'Labor'), ('subcontractor', 'Subcontractor'), ('commission', 'Commission/markup'), ('tax', 'Tax'), ('allowance', 'Allowance'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('incurred_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cost_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_entries', to='projects.costcode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_entries', to='projects.project')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_cost_entries_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-incurred_date', '-pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='projects_cost_entry_amount_positive')],
            },
        ),
    ]
