# Generated by Django 6.0.3 on 2026-08-03 12:12

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_estimate_replaces_alter_activityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='subtotal_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estimate',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='estimate',
            name='tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Tax percentage, e.g. 7.250 for 7.25%. Tax is computed automatically from this rate.', max_digits=6),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Default sales tax percentage applied to new invoice and estimate drafts, e.g. 7.250 for 7.25%.', max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='estimate',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0), ('tax_rate__lte', 100)), name='projects_estimate_tax_rate_within_range'),
        ),
    ]
