# Generated by Django 6.0.3 on 2026-08-05 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeorder',
            name='source_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_change_orders', to='projects.finishselection'),
        ),
    ]
