# Generated by Django 6.0.3 on 2026-08-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('projects', '0014_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksconnection',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='capabilities_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='country',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='offering_sku',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='quickbooksconnection',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='QuickBooksProjectCustomerMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_customer_id', models.CharField(max_length=50)),
                ('quickbooks_sync_token', models.CharField(blank=True, max_length=50)),
                ('quickbooks_display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unlinked', 'Unlinked'), ('tombstoned', 'Removed in QuickBooks')], default='active', max_length=20)),
                ('external_active', models.BooleanField(default=True)),
                ('ownership_policy', models.CharField(choices=[('quickbooks_authoritative', 'QuickBooks is authoritative')], default='quickbooks_authoritative', max_length=40)),
                ('conflict_policy', models.CharField(default='quickbooks_wins', editable=False, max_length=40)),
                ('last_synced_values', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_customer_mappings', to='integrations.quickbooksconnection')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_customer_mapping', to='projects.project')),
            ],
            options={
                'ordering': ('project__name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('connection', 'quickbooks_customer_id'), name='integrations_unique_active_project_customer')],
            },
        ),
    ]
