# Generated by Django 6.0.3 on 2026-08-01 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_quickbooksconnection_capabilities_and_more'),
        ('projects', '0015_alter_activityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksSyncAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('customer', 'Customer')], max_length=20)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update')], max_length=20)),
                ('direction', models.CharField(choices=[('to_quickbooks', 'To QuickBooks'), ('from_quickbooks', 'From QuickBooks')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('resolved', 'Resolved')], max_length=20)),
                ('operation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('external_id', models.CharField(blank=True, max_length=50)),
                ('external_sync_token', models.CharField(blank=True, max_length=50)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('retryable', models.BooleanField(default=False)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_attempts', to='integrations.quickbooksconnection')),
                ('mapping', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='integrations.quickbooksprojectcustomermapping')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickbooks_sync_attempts', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickbooks_sync_attempts_requested', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickbooks_sync_attempts_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='integrations_sync_retry_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'operation_key', 'attempt_number'), name='integrations_unique_sync_attempt_number'), models.UniqueConstraint(condition=models.Q(('status', 'running')), fields=('connection', 'entity_type', 'direction'), name='integrations_unique_running_entity_sync')],
            },
        ),
    ]
