# Generated by Django 6.0.3 on 2026-08-01 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('integrations', '0003_quickbookssyncattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookssyncattempt',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickbooks_sync_attempts', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='quickbookssyncattempt',
            name='entity_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('invoice', 'Invoice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quickbookssyncattempt',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('void', 'Void')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuickBooksInvoiceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_invoice_id', models.CharField(max_length=50)),
                ('quickbooks_sync_token', models.CharField(max_length=50)),
                ('quickbooks_customer_id', models.CharField(max_length=50)),
                ('quickbooks_doc_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided in QuickBooks'), ('tombstoned', 'Removed in QuickBooks')], default='active', max_length=20)),
                ('ownership_policy', models.CharField(choices=[('quickbooks_authoritative', 'QuickBooks is authoritative after first sync')], default='quickbooks_authoritative', max_length=40)),
                ('conflict_policy', models.CharField(default='quickbooks_wins', editable=False, max_length=40)),
                ('external_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('external_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('external_txn_date', models.DateField(blank=True, null=True)),
                ('external_due_date', models.DateField(blank=True, null=True)),
                ('currency_code', models.CharField(blank=True, max_length=10)),
                ('last_synced_values', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('external_voided_at', models.DateTimeField(blank=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_mappings', to='integrations.quickbooksconnection')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quickbooks_mapping', to='billing.invoice')),
            ],
            options={
                'ordering': ('-last_synced_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='quickbookssyncattempt',
            name='invoice_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='integrations.quickbooksinvoicemapping'),
        ),
        migrations.AddConstraint(
            model_name='quickbooksinvoicemapping',
            constraint=models.UniqueConstraint(fields=('connection', 'quickbooks_invoice_id'), name='integrations_unique_quickbooks_invoice'),
        ),
        migrations.AddConstraint(
            model_name='quickbooksinvoicemapping',
            constraint=models.CheckConstraint(condition=models.Q(('external_total_amount__isnull', True), ('external_total_amount__gte', 0), _connector='OR'), name='integrations_qbo_invoice_total_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='quickbooksinvoicemapping',
            constraint=models.CheckConstraint(condition=models.Q(('external_balance__isnull', True), ('external_balance__gte', 0), _connector='OR'), name='integrations_qbo_invoice_balance_nonnegative'),
        ),
    ]
