# Generated by Django 6.0.3 on 2026-08-03 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_quickbookssyncattempt_invoice_and_more'),
        ('projects', '0022_alter_activityevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbookssyncattempt',
            name='cost_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quickbooks_sync_attempts', to='projects.costcode'),
        ),
        migrations.AlterField(
            model_name='quickbookssyncattempt',
            name='entity_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('invoice', 'Invoice'), ('item', 'Item')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuickBooksItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_item_id', models.CharField(max_length=50)),
                ('quickbooks_sync_token', models.CharField(blank=True, max_length=50)),
                ('quickbooks_item_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('unlinked', 'Unlinked'), ('tombstoned', 'Removed in QuickBooks')], default='active', max_length=20)),
                ('external_active', models.BooleanField(default=True)),
                ('ownership_policy', models.CharField(choices=[('quickbooks_authoritative', 'QuickBooks is authoritative')], default='quickbooks_authoritative', max_length=40)),
                ('conflict_policy', models.CharField(default='quickbooks_wins', editable=False, max_length=40)),
                ('last_synced_values', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_code_item_mappings', to='integrations.quickbooksconnection')),
                ('cost_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quickbooks_item_mapping', to='projects.costcode')),
            ],
            options={
                'ordering': ('cost_code__code',),
            },
        ),
        migrations.AddField(
            model_name='quickbookssyncattempt',
            name='item_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='integrations.quickbooksitemmapping'),
        ),
        migrations.AddConstraint(
            model_name='quickbooksitemmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('connection', 'quickbooks_item_id'), name='integrations_unique_active_cost_code_item'),
        ),
    ]
