# Generated by Django 6.0.3 on 2026-08-05 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_invoice_tax_rate_and_more'),
        ('integrations', '0005_quickbookssyncattempt_cost_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickbookssyncattempt',
            name='entity_type',
            field=models.CharField(choices=[('customer', 'Customer'), ('invoice', 'Invoice'), ('item', 'Item'), ('payment', 'Payment')], max_length=20),
        ),
        migrations.CreateModel(
            name='QuickBooksPaymentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_payment_id', models.CharField(max_length=50)),
                ('quickbooks_sync_token', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided in QuickBooks'), ('tombstoned', 'Removed in QuickBooks')], default='active', max_length=20)),
                ('external_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_synced_values', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_mappings', to='integrations.quickbooksconnection')),
                ('invoice_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_mappings', to='integrations.quickbooksinvoicemapping')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quickbooks_mapping', to='billing.payment')),
            ],
            options={
                'ordering': ('-last_synced_at', '-pk'),
            },
        ),
        migrations.AddField(
            model_name='quickbookssyncattempt',
            name='payment_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_attempts', to='integrations.quickbookspaymentmapping'),
        ),
        migrations.AddConstraint(
            model_name='quickbookspaymentmapping',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('connection', 'quickbooks_payment_id', 'invoice_mapping'), name='integrations_unique_quickbooks_payment'),
        ),
        migrations.AddConstraint(
            model_name='quickbookspaymentmapping',
            constraint=models.CheckConstraint(condition=models.Q(('external_amount__isnull', True), ('external_amount__gte', 0), _connector='OR'), name='integrations_qbo_payment_amount_nonnegative'),
        ),
    ]
