# Generated by Django 6.0.3 on 2026-08-05 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_payment_method_creditmemo_payment_credit_memo_and_more'),
        ('integrations', '0006_alter_quickbookssyncattempt_entity_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksCreditMemoMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quickbooks_credit_memo_id', models.CharField(max_length=50)),
                ('quickbooks_sync_token', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('voided', 'Voided in QuickBooks'), ('tombstoned', 'Removed in QuickBooks')], default='active', max_length=20)),
                ('external_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('last_synced_values', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('tombstoned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memo_mappings', to='integrations.quickbooksconnection')),
                ('invoice_mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_memo_mappings', to='integrations.quickbooksinvoicemapping')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='quickbooks_credit_memo_mapping', to='billing.payment')),
            ],
            options={
                'ordering': ('-last_synced_at', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('connection', 'quickbooks_credit_memo_id', 'invoice_mapping'), name='integrations_unique_quickbooks_credit_memo'), models.CheckConstraint(condition=models.Q(('external_amount__isnull', True), ('external_amount__gte', 0), _connector='OR'), name='integrations_qbo_credit_memo_amount_nonnegative')],
            },
        ),
    ]
