# Generated by Django 6.0.3 on 2026-08-01 18:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0017_alter_activityevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('event_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=255)),
                ('livemode', models.BooleanField()),
                ('api_version', models.CharField(blank=True, max_length=40)),
                ('outcome', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored')], max_length=12)),
                ('created_at_stripe', models.DateTimeField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('not_started', 'Not started'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='not_started', max_length=24)),
                ('livemode', models.BooleanField(default=False)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('past_due_since', models.DateTimeField(blank=True, null=True)),
                ('last_invoice_id', models.CharField(blank=True, max_length=255)),
                ('last_invoice_status', models.CharField(blank=True, max_length=40)),
                ('last_stripe_event_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='projects.organization')),
            ],
            options={
                'ordering': ('organization__name',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_customer_id', ''), _negated=True), fields=('stripe_customer_id',), name='subscriptions_unique_stripe_customer'), models.UniqueConstraint(condition=models.Q(('stripe_subscription_id', ''), _negated=True), fields=('stripe_subscription_id',), name='subscriptions_unique_stripe_subscription')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCheckoutAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, max_length=255)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('checkout_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('open', 'Open'), ('complete', 'Complete'), ('expired', 'Expired')], default='creating', max_length=12)),
                ('livemode', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_checkout_attempts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_checkout_attempts', to='projects.organization')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('stripe_checkout_session_id', ''), _negated=True), fields=('stripe_checkout_session_id',), name='subscriptions_unique_checkout_session')],
            },
        ),
    ]
